services:
  back:
    build: https://github.com/Katy248/electrotech.git
    volumes:
      - data:/data
      - database:/database
    ports:
      - "8080:8080"
      - "8021:8021"
      - "30000-30020:30000-30020"
    env_file:
      - .env
  front:
    build: https://github.com/icentr/electrotech-front.git
    ports:
      - "80:3000"
    env_file:
      - .env

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: "/var/data"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "/var/database"
      o: bind
