services:
  back:
    build: https://github.com/Katy248/electrotech.git
    volumes:
      - data:/data
      - database:/database
    ports:
      - "8080:8080"
      - "8021:8021"
      - "30000-30020:30000-30020"
    env_file:
      - .env
  front:
    build: https://github.com/icentr/electrotech-front.git
    ports:
      - "3000:3000"
    env_file:
      - .env
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: "/var/data"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "/var/database"
      o: bind
