services:
  back:
    build: git://github.com/Katy248/electrotech.git#main
    volumes:
      - data:/data
      - database:/database.sqlite3
    ports:
      - "8080:8080"
      - "8021:8021"
      - "30000-30020:30000-30020"
    env_file:
      - .env
  front:
    build: git://github.com/icentr/electrotech-front#main
    ports:
      - "80:3000"

volumes:
  data:
    driver: local
    driver_opts:
      device: "/var/data"
  database:
    driver: local
    driver_opts:
      device: "/database.sqlite3"
